all:
	quarto render

lettre:
	quarto render lettre.qmd

lettre-noheadfoot:
	quarto render lettre-noheadfoot.qmd

compte-rendu:
	quarto render compte-rendu.qmd

document:
	quarto render document.qmd

clean:
	rm -rf _output
